# Generated by Django 3.1.4 on 2020-12-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='img',
            field=models.ImageField(blank=True, upload_to='media/images/', verbose_name='Фотография'),
        ),
    ]
